# Change these first
owner: omxpro # Your GitHub organization or username, where this repository lives
repo: dozen-cord-status # The name of this repository

sites:
  - name: DozenCord Web Client
    url: http://173.208.153.242:1131
  - name: DozenCord Status Page
    url: https://github.com/omxpro/dozen-cord-status
  - name: DozenCord CDN
    url: https://cdn.dozen-cord.cf
  - name: Fosscord-server official unstable site
    url: https://dev.fosscord.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: 
  # baseUrl: /dozen-cord-status
  logoUrl: https://tinyurl.com/dozencordlogo
  name: DozenCord
  introTitle: "**DozenCord** is a remix selfhosted version of Discord!"
  introMessage: Bored of that old laggy discord filled with bugs? Try DozenCord now! It's not laggy it has less bugs and it has better support! For more info join our discord server!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
