# Change these first
owner: omxpro # Your GitHub organization or username, where this repository lives
repo: dozen-cord-status # The name of this repository

sites:
  - name: DozenCord Web Client
    url: http://173.208.153.242:1131
  - name: DozenCord Status Page
    url: https://github.com/omxpro/dozen-cord-status
  - name: DozenCord CDN
    url: https://cdn.dozen-cord.cf
  - name: Fosscord-server official unstable site
    url: https://

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /dozen-cord-status
  logoUrl: https://tinyurl.com/dozencordlogo
  name: DozenCord
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
