# Change these first
owner: omxpro # Your GitHub organization or username, where this repository lives
repo: DozenCordStatus # The name of this repository

sites:
  - name: DozenCord
    url: http://173.200.153.242:1131
  - name: DozenCord Beta
    url: https://beta.dozen-cord.cf
  - name: DozenCord StatusPage 
    url: https://github.com/omxpro/Status
  - name: DozenCord CDN
    url: https://cdn.dozen-cord.cf
  - name: DozenCord API
  - url: https://api.dozen-cord.cf

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://tinyurl.com/DozenCordLogo
  name: DozenCord
  introTitle: "**DozenCord** is a selfhosted Discord version"
  introMessage: "Bored of that old Laggy discord? Try our own selfhosted DozenCord right now!"
   navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
